difficulty: 1
ellipticcurve: !!binary |
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5LK54+OuLJEpFziPP/vaJddr3i8ka/GheI
    so0iZFxfejSYOTSiW9XbNuNkvbLP1SjOezmapnva61uHmzvozXFg==
ftype: 0
node0_ip: "0"
node0_pk: "0"
node1_ip: "0"
node1_pk: "0"
node2_ip: "0"
node2_pk: "0"
node3_ip: "0"
node3_pk: "0"
running: true
tctype: 0
version: v6.0
vrftype: 0
