difficulty: 1
ellipticcurve: !!binary |
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5LK54+OuLJEpFziPP/vaJddr3i8ka/GheI
    so0iZFxfejSYOTSiW9XbNuNkvbLP1SjOezmapnva61uHmzvozXFg==
ftype: 0
node0_ip: 1.116.151.179
node0_pk: "30000"
node1_ip: 1.116.151.179
node1_pk: "30001"
node2_ip: 152.136.151.161
node2_pk: "30000"
node3_ip: 152.136.151.161
node3_pk: "30001"
running: true
tctype: 0
version: v6.0
vrftype: 0
